### ISSUE TITLE
Amazing Bug With Forge 2304

### ISSUE THREAD

**Issue by kenijey** [tterrag1098/Blur#1]
hello. installed ONLY this mod, and setting the max-frame-rate option to unlimited, then press ESC to see the menu gui, aand minimize the minecraft window; minecraft ram usage increases regular forever.
normally, it uses 1600 MB in task manager, but when do that i told, it increases per second 1800..2000...2220...2540...(MB)
please help it :( 
and it fixes when i set the max frame rate to the 60.

**Comment by kenijey** [comment]
and i can record a video if you want. only Blur mod is installed on clean install of Vanilla (no resource pack, etc)

**Comment by tterrag1098** [comment]
Sorry, in the video it's only vanilla? How did you come to the conclusion that this is caused by my mod?

**Comment by kenijey** [comment]
because it happens only your mod is installed.

**Comment by tterrag1098** [comment]
I do not do anything in this mod that would cause such memory issues, to my knowledge.

I'm going to need more evidence than a video from 3 months ago showing a vaguely similar issues. Please compare memory usage with and without the mod, in a way that can easily be reproduced.
