### ISSUE TITLE
doesn't apply blur with optifine & forge

### ISSUE THREAD

**Issue by mrstandu33** [tterrag1098/Blur#11]
Hi, I'm facing a strange bug. I've got forge 1.11.2-13.20.0.2259 (latest at this date), Minecraft 1.11.2 and Optifine HD C2 ultra (latest at this date) but blur mod (1.0.1-9) won't show any blur effect. I've put the mod in mod folder as it needs.

When I go in the texture pack option and I modify something and apply changes, I've got blur effect on the "escape menu". But blur won't show up all other times.

I noticed than when I remove Optifine, everything works perfectly ... But you says than your mod works with shaders ... How ?

And, of course, the Fast Render option is disabled. 

My shader pack is Sildurs Vibrant Extreme.

Sorry for my bad english, I'm from france ^^.

**Comment by CyanideX** [comment]
Well, forge version 13.20.0.2366 is actually the latest at at this date for Minecraft 1.11.2.

I'm using the latest Optifine for 1.11.2 with a resource pack enabled and everything works perfectly.

![Iron Chests GUI](http://i.imgur.com/chlKLf5.png)

**Comment by CyanideX** [comment]
Try updating Blur from 1.0.1-9 to the latest version: 1.0.2-10.

**Comment by Nelly1234567** [comment]
I'm having the same problem, i have forge 12.20.1.2393, running the newest version of the mod and have the newest version of optifine. The mod works for only certain things, when i look in someones inv with /invsee on servers and sometimes when i'm in the esc menu. other then that it wont work but for some reason a mod pack with the same mods and more that wasn't made by me works perfectly fine. Is there some sort of trick to setting it up? because just having it installed just doesn't seem to work right.

**Comment by mrstandu33** [comment]
I just Found the solution ! It was "antialiasing" option in my shaderpack. Once I disabled that, it start working :D. If it doesn't help you Nelly1234567 I can help you ;)

**Comment by TimGoll** [comment]
thank you @mrstandu33 
I've debugged FOR HOURS until I found your comment. @tterrag1098 should add this to the mod description.

**Comment by tterrag1098** [comment]
Ask the optifine dev, I'm only using vanilla shaders...

**Comment by mrstandu33** [comment]
Do i close this ticket @tterrag1098 Or we let it open as it still does not work with Optifine's AntiAliasing option ?

**Comment by TimGoll** [comment]
Since optifine will never fix this... yes

**Comment by Nelly1234567** [comment]
Close it, a lot of shaders have AntiAliasing included in them so optifine doesn't need to change much or anything with that.

**Comment by mrstandu33** [comment]
As asked, Issue closed. Keep in mind you have to disable Optifine's "AntiAliasing" option.
