### ISSUE TITLE
[1.10.2] Blur is not working but fade is.

### ISSUE THREAD

**Issue by LaureeGrd** [tterrag1098/Blur#14]
Hi, I installed this mod and even when the fade option (and colors) is working properly, it is not getting blurry.
I tried it without optifine and betterfps (the only render-changing mods I'm using) and it still doesn't work. Will try it later without ANY other mod but, is there something I should be aware of?

EDIT: It does work without any other mods. How can I give you a complete list of my mods without having to screenshot the folder (which would be very messy to see)?

**Comment by tterrag1098** [comment]
Have you checked the other issues? Some incompatibilities have already been found.

**Comment by LaureeGrd** [comment]
I disabled Natural Pledge and it and it works now. Thanks. Sorry for posting an issue without checking the closed ones!
