### ISSUE TITLE
The Blur effect doesn't work with Fast Render

### ISSUE THREAD

**Issue by agentdouble0** [tterrag1098/Blur#15]
When I have fast render on (from optifine) the blur effect doesn't work. But when I turn fast render off the blur effect works just fine. If possible fix soon! 👍

**Comment by tterrag1098** [comment]
No, Optifine. and especially fast render, is not and won't be supported.

**Comment by CyanideX** [comment]
Optifine's fast render option is there to increase performance by using an alternate rendering method that removes certain fancy rendering... what did you expect? Blur is fancy. It goes bye-bye if you choose to remove fanciness.
