### ISSUE TITLE
(1.12) Poof! crashes.

### ISSUE THREAD

**Issue by Migmag789** [tterrag1098/Blur#16]
I'm launching my modpack and... Poof! crashes.
[crash-2017-07-17_11.03.47-client.txt](https://github.com/tterrag1098/Blur/files/1152060/crash-2017-07-17_11.03.47-client.txt)
I'm adverting all the other mod authors ;)

**Comment by tterrag1098** [comment]
This is a bug with MalisisCore, not Blur.
