### ISSUE TITLE
Doesn't blur rather just slightly darkens it

### ISSUE THREAD

**Issue by MisterQuiggly** [tterrag1098/Blur#17]
**Not blurring GUI, just slightly darkening it**

  * **Minecraft version:** *1.12.*
  * **Involved mods:** *OptiFine 1.12 HD U C4 and Forge 14.21.1.2387*

All information in the title, went into config, adjusted it past 12 and it didn't change anything. Its just slightly darkened

https://i.imgur.com/MgaZfZN.png

**Comment by tterrag1098** [comment]
Optifine is not supported. Some of its settings disable shaders and there is nothing I can do to get around that.

**Comment by Snuggle** [comment]
Turn off "Fast Render" in your Optifine settings to fix this, @MisterQuiggly.
