### ISSUE TITLE
Minecraft doesn't start with Blur-1.0.3-13, MC 1.12.1 and Forge #2444

### ISSUE THREAD

**Issue by bl4ckscor3** [tterrag1098/Blur#18]
I think a quick picture explains this, really weird, problem the best.
http://i.imgur.com/fSZOlgp.png

Other mods I have installed are SecurityCraft v1.8.2.3-hotfix, WoodConverter v2.9.2 and GlobalXP v1.2.1 (all mods that I'm working on, was testing if they work for 1.12.1).

**Comment by CyanideX** [comment]
You should post your log as well.

**Comment by bl4ckscor3** [comment]
Yes, that would have been a good idea. Will think of that next time.
1.0.4 works, however, so I'm closing this.
