### ISSUE TITLE
[1.7.10] Blur creates weird effect on other mod hud elements

### ISSUE THREAD

**Issue by KryptonCaptain** [tterrag1098/Blur#2]
![image](https://cloud.githubusercontent.com/assets/8790829/26480484/9f841076-420c-11e7-941a-a63bcd136f04.png)

As visible in the image, Blur creates some oddities with Tinker's Construct coloured hearts, Armor Chroma's changed bar and AppleCore's saturation display.

**Comment by tterrag1098** [comment]
As I don't manipulate the render state myself, other than telling vanilla to use a specific shader, I would guess that these mods are not properly setting up the state they need. It will need more investigation to find out just what flag is causing this.

CC @bonii-xx @squeek502

**Comment by tterrag1098** [comment]
Ok, I found the most probable cause. When there is a shader active, vanilla executes this code before doing any rendering:

```java
    private void preLoadShader()
    {
        GlStateManager.color(1.0F, 1.0F, 1.0F, 1.0F);
        GlStateManager.disableBlend();
        GlStateManager.disableDepth();
        GlStateManager.disableAlpha();
        GlStateManager.disableFog();
        GlStateManager.disableLighting();
        GlStateManager.disableColorMaterial();
        GlStateManager.enableTexture2D();
        GlStateManager.bindTexture(0);
    }
```

Judging by the screenshots, I'd guess that blending is disabled and these mods are not re-enabling it and assuming it to already be enabled. This is a fine assumption (apparently) unless shaders are involved.

**Comment by bonii-xx** [comment]
In general you can assume that the state is as vanilla passes it to you... unless another mod doesn't reset it back after changing it.

**Comment by tterrag1098** [comment]
In this case it is vanilla. I do not directly modify *any* GL state in this mod.

**Comment by bonii-xx** [comment]
Curious. Ah the vanilla shader thing setup. Yeah, I see what you mean.

**Comment by tterrag1098** [comment]
I've also just noticed that this issue is tagged 1.7.10, so I understand if you don't care to debug any further. @KryptonCaptain if you can verify this also occurs on 1.10/1.11 then maybe more can be done.

**Comment by bonii-xx** [comment]
Doesn't seem to happen in 1.10+ as far as I can tell. Probably a 1.7 relict. And yes I'm not going to touch 1.7, we stopped supporting that.. a year ago or so?

**Comment by tterrag1098** [comment]
👍

**Comment by KryptonCaptain** [comment]
I get that, latest version trend and whatnot. But if you can give me a pointer for how I'd fix it for my own version, that'd be appreciated

**Comment by tterrag1098** [comment]
There's not much you can do, the mods have a bug.

**Comment by KryptonCaptain** [comment]
I meant for TCon, since I already have a custom build of that running. If I know what to target in one mod, I could probably make a custom build to fix the others.
