### ISSUE TITLE
1.12.1 wont work

### ISSUE THREAD

**Issue by kenijey** [tterrag1098/Blur#20]
![faf](https://user-images.githubusercontent.com/24831406/30065111-88d3feea-925c-11e7-9472-b97b5679173e.PNG)

forge 2469

**Comment by tterrag1098** [comment]
There is an update that addresses this.

**Comment by kenijey** [comment]
where?

**Comment by tterrag1098** [comment]
1.0.4 which was uploaded specifically for this reason: https://minecraft.curseforge.com/projects/blur/files/2460821

**Comment by kenijey** [comment]
omg, this is insane. i already downloaded that file but i redownloaded and now it works. i even checked the version, i used 1.0.4 in the issue run. dunno.
sry
