### ISSUE TITLE
CPU fan going on a party

### ISSUE THREAD

**Issue by TheKrister2** [tterrag1098/Blur#23]
Couldn't really think of a good title, sorry 'bout that. I've used blur before, and it is amazing as usual. Something I've noticed this time around though, is that if I stay in a menu where blur is active for a little while, my CPU fan spins up like crazy.

This isn't really an _issue_ per se, however I wanted to know if you've experienced something similar and what the causes might be. So this is essentially a question, though I'm sorry if I'm asking in the wrong place.

My cpu temperatures seem to be holding just fine, going a few degrees lower than normal. But it seems only the fan itself goes crazy.

**Comment by tterrag1098** [comment]
The blur shader can be a little intensive depending on your specific GPU. If you have integrated graphics, it could cause your CPU to spin up. I'd advise you try turning the blur radius down a bit.

**Comment by TheKrister2** [comment]
Alright, I guess that makes sense. Though haven't had this issue before. Luckily I do not use integrated graphics though. Thanks for the quick reply.
