### ISSUE TITLE
Minecolonies support?

### ISSUE THREAD

**Issue by Pulz-TCP** [tterrag1098/Blur#30]
I don't suppose there is any way to have the blur disabled when using Minecolonies' placement system?

The blur makes it rather difficult to see where you're going to be placing a colony.
Reference: https://youtu.be/DVGGDUXbTOY?t=18

**Comment by tterrag1098** [comment]
Add `com.minecolonies.blockout.Screen` to your GUI exclusions, as far as I can tell they use this class for all of their GUIs so it will prevent Blur from working on any of them. But there's no way to filter it further.

**Comment by Pulz-TCP** [comment]
> Add `com.minecolonies.blockout.Screen` to your GUI exclusions, as far as I can tell they use this class for all of their GUIs so it will prevent Blur from working on any of them. But there's no way to filter it further.

Thanks, this does indeed remove the blur from the minecolonies blur. 
Posting to confirm the fix for anyone else who comes across this.
