### ISSUE TITLE
Blur & CraftPresence conflicts

### ISSUE THREAD

**Issue by ox0Panda0xo** [tterrag1098/Blur#34]
Blur does not play well with CP's(CraftPresence) GUI.
Crashes the minecraft client completely if one presses the default GUI button (Key: Left Control).

> Client Info

 Fabric Loader: 0.6.3+ Build 167-1.14.4
 Minecraft Version: 1.14.4
   Mods: 
     Fabric API 0.4.0 Build 240
     CraftPresence 1.5.5
     Blur 1.0.5

[Crash Log.txt](https://github.com/tterrag1098/Blur/files/3720082/Crash.Log.txt)

**Comment by tterrag1098** [comment]
This is a bug in CraftPresence, it's opening a GUI in a different thread.

**Comment by CDAGaming** [comment]
This issue has now been fixed and will be included in CraftPresence v1.5.6, set for release within the next few days, provided nothing comes up. @ox0Panda0xo
