### ISSUE TITLE
No blur effect

### ISSUE THREAD

**Issue by Alan19** [tterrag1098/Blur#4]
I'm not getting a blur effect in GUIs but the background isn't as dark as vanilla. Can a resource pack cause the mod to work incorrectly? I'm using Unity.

![2017-05-27_23 38 19](https://cloud.githubusercontent.com/assets/11682762/26525965/40bbf330-4336-11e7-9fea-634a0c140ce5.png)

**Comment by bl4ckscor3** [comment]
Maybe you have Optifine's Fast Render setting enabled? I found that causes Blur to not work correctly.

**Comment by Alan19** [comment]
I don't have optifine installed

**Comment by tterrag1098** [comment]
Unity was tested with (it's used in the demo pictures on the mod page). The only known conflicts are OF fast render, and @yrsegal's Natural Pledge. It's possible that some other mod is causing an issue though.

**Comment by Alan19** [comment]
I have natural pledge installed

**Comment by yrsegal** [comment]
NP will be fixed in next release, likely by Tuesday.

**Comment by yrsegal** [comment]
I'd love for it to be fixed sooner, but i'm waiting on models >.>

**Comment by Alan19** [comment]
By the way, I'm currently on 1.10
