### ISSUE TITLE
[1.8.9] Exclusions List doesn't seem to work

### ISSUE THREAD

**Issue by LlamaLad7** [tterrag1098/Blur#42]
Even when the Chat is in the exclusions list, it still blurs the background when you have it open

**Comment by Froxcey** [comment]
Same here

**Comment by LlamaLad7** [comment]
You probably have optifine which replaces the chat gui so you'll need to use its gui name instead

**Comment by Froxcey** [comment]
Found it. Just add net.optifine.gui.ChatOF to the list. Thank you for your help :)
