### ISSUE TITLE
Game crashes upon using this mod. Didn't change anything.

### ISSUE THREAD

**Issue by MagmaSlime123** [tterrag1098/Blur#47]
[crash-2020-05-20_21.55.18-server.txt](https://github.com/tterrag1098/Blur/files/4670974/crash-2020-05-20_21.55.18-server.txt)

Mods listed in the crash report file. Adding the mod to my mods folder and starting, causes the crash. Didn't even configure nor touch this mod yet.

**Comment by tterrag1098** [comment]
That's a serverside crash that can't be caused by Blur, sorry.

**Comment by MagmaSlime123** [comment]
I'm not on any server, nor does anything occur without the mod.

**Comment by tterrag1098** [comment]
There's always a server even in single player. This is just a random crash caused by some mod. It's random chance that it hasn't happened without Blur. I assure you there's no way Blur could interfere and cause this.
