### ISSUE TITLE
REALLY HUGE ISSUE!!!

### ISSUE THREAD

**Issue by ScottKillen** [tterrag1098/Blur#5]
This is the mod I never knew I needed...but I do. _Thank you!_

**_But_** I now have a Really Big Issue ™️: I'm so immersed in my GUIs now that I realize how unattractive they are. How should I solve this? 😀

**Comment by CyanideX** [comment]
I had been looking for a developer to create this mod for me for about two years! Then, one day, someone randomly mentioned it to @tterrag1098 and he said "Oh, I could probably make that". Two hours later... Blur was born.

I share your emotions, Scott. This was my dream mod and he's managed to make it all happen in the blink of an eye. 😛

**Comment by ScottKillen** [comment]
Good to see you again! It has been a while since I have been 'round these parts.

Yeah...this is really genius. 🏆
