### ISSUE TITLE
No blur but fade is working in Roguelike Adventures and Dungeons mod pack

### ISSUE THREAD

**Issue by Juanescacha** [tterrag1098/Blur#59]
i have read all the issues and I dont know what mod is the one that is making the "incompatibility" i checked optifine and is not him.
this mod pack has many mod, so is a little tricky to check 1 by 1
The only thing that works on GUIS is the fade to a little dark, on JEI and pause menu.

Interesting Fact: When I go to the pause menu (ESC) only fade works...... but ........ when I lost the focus of the minecraft window and change to another aplication (thing that forces pause menu) the BLUR works, only in that way and in this menu only, why? i dont know, Thanks for your help!

**Comment by tterrag1098** [comment]
There can only be one active screen shader, so if another mod is forcing theirs to be active all the time, blur won't work. I also can't say what mod it is, unfortunately.
