### ISSUE TITLE
Adding exclusions

### ISSUE THREAD

**Issue by luckeYpublic** [tterrag1098/Blur#71]
Hi!
Is it possible to add the F3+Esc pause screen to exclusions?

**Comment by luckeYpublic** [comment]
If anyone is wondering the same, I found out that it's the net.minecraft.class_433

**Comment by ScuseMyFrench** [comment]
Hi, is there a way of getting the F3 + Esc pause screen to exclusions but still have the in game menu screen background to blur? Thanks :)
