### ISSUE TITLE
Flan's Mod Vehicle Incompatibility

### ISSUE THREAD

**Issue by dondonini** [tterrag1098/Blur#9]
Great mod! I love this thing to bits!

Anyways, when I sit in vehicles in any content pack in Flan's Mod. I end up driving blind. Is there any way to disable the blur while riding any vehicle?
It might be the same for boats and minecarts, but I haven't tried those yet.

**Comment by tterrag1098** [comment]
Flan's must be popping a GUI when the user is inside a vehicle. The only way to fix would be to find the class name of this GUI and add it to the exclusions.
